In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import csv

input_file = "nutrient_query_qwen.csv"
output_file = "nutrient_query_qwen_clean.csv"

with open(input_file, "r", encoding="utf-8", newline="") as infile, \
     open(output_file, "w", encoding="utf-8", newline="") as outfile:

    reader = csv.reader(infile)
    writer = csv.writer(outfile, quoting=csv.QUOTE_MINIMAL)

    for row in reader:
        cleaned_row = []
        for field in row:
            if ',' in field and not (field.startswith('"') and field.endswith('"')):
                # Wrap field in quotes if it contains a comma and isn't already quoted
                cleaned_row.append(field)
            else:
                cleaned_row.append(field)
        writer.writerow(cleaned_row)

print(f"Cleaned CSV saved to {output_file}")

FileNotFoundError: [Errno 2] No such file or directory: 'nutrient_query_qwen.csv'

In [1]:

df1 = pd.read_csv("nutrient_query_qwen_clean.csv")
print(df1.head())

NameError: name 'pd' is not defined

In [7]:
import csv

file_path = "nutrient_query_qwen.csv"

# Read raw and inspect field counts
with open(file_path, "r", encoding="utf-8") as f:
    reader = csv.reader(f)
    rows = list(reader)

expected_cols = len(rows[0])
print(f"Expected number of columns: {expected_cols}\n")

for i, row in enumerate(rows, start=1):
    if len(row) != expected_cols:
        print(f"Row {i} has {len(row)} columns: {row}")

Expected number of columns: 7

Row 9 has 9 columns: ['8', 'Which African staple has lowest phytate: fufu', ' ugali', ' or banku?', 'comparison', '3', 'TinyLlama', 'True', '']
Row 17 has 9 columns: ['16', 'Which traditional fermentation method reduces phytate most: ogi', ' akamu', ' or kenkey?', 'comparison', '4', 'Mistral', 'True', '']
Row 37 has 9 columns: ['36', 'Which traditional preparation lowers phytate most: ogi', ' akamu', ' or kenkey?', 'comparison', '4', 'Mistral', 'True', '']
Row 57 has 9 columns: ['56', 'Which traditional preparation lowers phytate most: ogi', ' akamu', ' or kenkey?', 'comparison', '4', 'Mistral', 'True', '']
Row 77 has 9 columns: ['76', 'Which traditional preparation lowers phytate most: ogi', ' akamu', ' or kenkey?', 'comparison', '4', 'Mistral', 'True', '']
Row 286 has 8 columns: ['285', 'My patient has gout with uric acid 9.2 mg/dL', ' what diet therapy should I prescribe?', 'therapy', '5', 'Mistral', 'False', '']
Row 401 has 9 columns: ['400', "Tell me what's in avocado â€” vitamins", ' minerals', ' etc.', 'general', '2', 'TinyLlama', 'False', '']
Row 447 has 9 columns: ['446', 'Which African staple has the lowest phytate: fufu', ' ugali', ' or banku?', 'comparison', '3', 'TinyLlama', 'True', '']

In [8]:
import csv

input_file = "nutrient_query_qwen.csv"
output_file = "nutrient_query_qwen_clean.csv"

with open(input_file, "r", encoding="utf-8", newline="") as infile, \
     open(output_file, "w", encoding="utf-8", newline="") as outfile:

    reader = csv.reader(infile)
    writer = csv.writer(outfile, quoting=csv.QUOTE_MINIMAL)

    header = next(reader)
    writer.writerow(header)

    expected_cols = len(header)

    for row in reader:
        if len(row) > expected_cols:
            # Merge everything between query (index 1) and label (last 5 columns from end)
            id_val = row[0]
            # The 'label' column is always followed by 4 more columns
            label_index_from_end = 5
            query_parts = row[1:len(row) - label_index_from_end]
            query_val = ", ".join(query_parts)  # merge back into one string
            rest = row[len(row) - label_index_from_end:]
            fixed_row = [id_val, query_val] + rest
            writer.writerow(fixed_row)

        elif len(row) < expected_cols:
            fixed_row = row + [""] * (expected_cols - len(row))
            writer.writerow(fixed_row)

        else:
            writer.writerow(row)

print(f"Cleaned CSV saved to {output_file}")

Cleaned CSV saved to nutrient_query_qwen_clean.csv

In [9]:

df1 = pd.read_csv("nutrient_query_qwen_clean.csv")
print(df1.head())

   id                                              query       label  \
0   1  Compare raw vs boiled bambara nut phytate content  comparison
1   2  Is millet or sorghum better for zinc absorptio...  comparison
2   3  Compare vitamin K levels in raw kale vs fermen...  comparison
3   4  Which has lower phytate: unfermented ogi or so...  comparison
4   5  Compare protein quality of cowpea vs bambara n...  comparison

   complexity recommended_llm  needs_followup distractor_label
0           3       TinyLlama            True              NaN
1           4         Mistral            True              NaN
2           3       TinyLlama            True              NaN
3           4         Mistral            True              NaN
4           3       TinyLlama            True              NaN

In [10]:
df1.head()

,id,query,label,complexity,recommended_llm,needs_followup,distractor_label
0,1,Compare raw vs boiled bambara nut phytate content,comparison,3,TinyLlama,True,NaN
1,2,Is millet or sorghum better for zinc absorptio...,comparison,4,Mistral,True,NaN
2,3,Compare vitamin K levels in raw kale vs fermen...,comparison,3,TinyLlama,True,NaN
3,4,Which has lower phytate: unfermented ogi or so...,comparison,4,Mistral,True,NaN
4,5,Compare protein quality of cowpea vs bambara n...,comparison,3,TinyLlama,True,NaN

In [13]:

input_file = "nutrient_query_qwen2.csv"
output_file = "nutrient_query_qwen2_clean.csv"

with open(input_file, "r", encoding="utf-8", newline="") as infile, \
     open(output_file, "w", encoding="utf-8", newline="") as outfile:

    reader = csv.reader(infile)
    writer = csv.writer(outfile, quoting=csv.QUOTE_MINIMAL)

    header = next(reader)
    writer.writerow(header)

    expected_cols = len(header)

    for row in reader:
        if len(row) > expected_cols:
            # Merge everything between query (index 1) and label (last 5 columns from end)
            id_val = row[0]
            # The 'label' column is always followed by 4 more columns
            label_index_from_end = 5
            query_parts = row[1:len(row) - label_index_from_end]
            query_val = ", ".join(query_parts)  # merge back into one string
            rest = row[len(row) - label_index_from_end:]
            fixed_row = [id_val, query_val] + rest
            writer.writerow(fixed_row)

        elif len(row) < expected_cols:
            fixed_row = row + [""] * (expected_cols - len(row))
            writer.writerow(fixed_row)

        else:
            writer.writerow(row)

print(f"Cleaned CSV saved to {output_file}")

Cleaned CSV saved to nutrient_query_qwen2_clean.csv

In [14]:
df2 = pd.read_csv("nutrient_query_qwen2_clean.csv")

In [15]:
df2.head()

,id,query,label,complexity,recommended_llm,needs_followup,distractor_label
0,1,What's the difference between raw and boiled b...,comparison,3,TinyLlama,True,NaN
1,2,Which gives better zinc absorption for childre...,comparison,4,Mistral,True,NaN
2,3,How does vitamin K in raw kale compare to ferm...,comparison,3,TinyLlama,True,NaN
3,4,Unfermented ogi or sourdough breadâ€”which has l...,comparison,4,Mistral,True,NaN
4,5,Which has better protein quality: cowpea or ba...,comparison,3,TinyLlama,True,NaN

In [16]:

# Load both datasets
df1 = pd.read_csv("nutrient_query_qwen_clean.csv")
df2 = pd.read_csv("nutrient_query_qwen2_clean.csv")

# Combine them vertically
df_combined = pd.concat([df1, df2], ignore_index=True)

# Reassign IDs starting from 1
df_combined['id'] = range(1, len(df_combined) + 1)

print(df_combined.head())
print(df_combined.tail())

# Optional: save combined dataset
df_combined.to_csv("nutrient_query_qwen_combined.csv", index=False)

   id                                              query       label  \
0   1  Compare raw vs boiled bambara nut phytate content  comparison
1   2  Is millet or sorghum better for zinc absorptio...  comparison
2   3  Compare vitamin K levels in raw kale vs fermen...  comparison
3   4  Which has lower phytate: unfermented ogi or so...  comparison
4   5  Compare protein quality of cowpea vs bambara n...  comparison

   complexity recommended_llm  needs_followup distractor_label
0           3       TinyLlama            True              NaN
1           4         Mistral            True              NaN
2           3       TinyLlama            True              NaN
3           4         Mistral            True              NaN
4           3       TinyLlama            True              NaN
        id                                              query       label  \
1195  1196  How does the phytate content compare between r...  comparison
1196  1197  How much chromium is in a cup of cooked broccoli?     general
1197  1198  What is the best diet for managing Crohn's dis...     therapy
1198  1199  Is it safe to take vitamin D supplements daily...     general
1199  1200          How much biotin is in a single large egg?     general

      complexity recommended_llm  needs_followup distractor_label
1195           4         Mistral            True          therapy
1196           2       TinyLlama           False   recommendation
1197           5         Mistral            True   recommendation
1198           3         Mistral            True          therapy
1199           2       TinyLlama           False   recommendation

In [17]:
len(df_combined)

1200

In [23]:
df_combined.head()

,id,query,label,complexity,recommended_llm,needs_followup,distractor_label
0,1,Compare raw vs boiled bambara nut phytate content,comparison,3,TinyLlama,True,NaN
1,2,Is millet or sorghum better for zinc absorptio...,comparison,4,Mistral,True,NaN
2,3,Compare vitamin K levels in raw kale vs fermen...,comparison,3,TinyLlama,True,NaN
3,4,Which has lower phytate: unfermented ogi or so...,comparison,4,Mistral,True,NaN
4,5,Compare protein quality of cowpea vs bambara n...,comparison,3,TinyLlama,True,NaN

In [19]:
df3 = pd.read_csv("nutrition_queries_dataset.csv")

In [20]:
df3.head()

,id,query,label,complexity,recommended_llm,needs_followup,distractor_label
0,1,Compare the phytate levels in brown rice and m...,comparison,5,Mistral,True,NaN
1,2,Compare the phytate levels in brown rice and q...,comparison,5,Mistral,True,NaN
2,3,Which has higher protein digestibility: lentil...,comparison,2,Mistral,True,NaN
3,4,Compare the phytate levels in cassava flour an...,comparison,5,TinyLlama,False,NaN
4,5,Compare the phytate levels in lentils and maiz...,comparison,2,Mistral,True,NaN

In [21]:
df4 = pd.read_csv("nutrition_queries_dataset_augmented.csv")

In [22]:
df4.head()

,id,query,label,complexity,recommended_llm,needs_followup,distractor_label
0,1,Examine the phytate concentrations in brown ri...,comparison,5,Mistral,True,NaN
1,2,Assess the phytate concentrations in brown ric...,comparison,5,Mistral,True,NaN
2,3,What contains greater protein digestibility: l...,comparison,2,Mistral,True,NaN
3,4,Evaluate the phytate amounts in cassava flour ...,comparison,5,TinyLlama,False,NaN
4,5,Assess the phytate concentrations in lentils a...,comparison,2,Mistral,True,NaN

In [26]:
# Load datasets
df_combined = pd.read_csv("nutrient_query_qwen_combined.csv")
df3 = pd.read_csv("nutrition_queries_dataset.csv")
df4 = pd.read_csv("nutrition_queries_dataset_augmented.csv")

# Combine vertically
new_df = pd.concat([df_combined, df3, df4], ignore_index=True)

# Reassign IDs starting from 1 using the total length of new_df
new_df['id'] = range(1, len(new_df) + 1)

print(new_df.head())
print(new_df.tail())

# Save combined dataset
new_df.to_csv("nutrient_queries.csv", index=False)

   id                                              query       label  \
0   1  Compare raw vs boiled bambara nut phytate content  comparison
1   2  Is millet or sorghum better for zinc absorptio...  comparison
2   3  Compare vitamin K levels in raw kale vs fermen...  comparison
3   4  Which has lower phytate: unfermented ogi or so...  comparison
4   5  Compare protein quality of cowpea vs bambara n...  comparison

   complexity recommended_llm  needs_followup distractor_label
0           3       TinyLlama            True              NaN
1           4         Mistral            True              NaN
2           3       TinyLlama            True              NaN
3           4         Mistral            True              NaN
4           3       TinyLlama            True              NaN
        id                                              query           label  \
3595  3596  Outline a clinical nutrition plan for managing...         therapy
3596  3597  Out of these, option shows more protein digest...      comparison
3597  3598  Contrast the effects of zinc gluconate and fis...      comparison
3598  3599  Design a dietary intervention for improving vi...         therapy
3599  3600  What is the best way to enhance vitamin B12 ab...  recommendation

      complexity recommended_llm  needs_followup distractor_label
3595           4         Mistral           False       comparison
3596           3       TinyLlama            True          therapy
3597           1       TinyLlama           False          therapy
3598           3         Mistral           False          general
3599           3         Mistral           False       comparison

In [25]:
len(new_df)

2400

In [27]:
new_df.head(10)

,id,query,label,complexity,recommended_llm,needs_followup,distractor_label
0,1,Compare raw vs boiled bambara nut phytate content,comparison,3,TinyLlama,True,NaN
1,2,Is millet or sorghum better for zinc absorptio...,comparison,4,Mistral,True,NaN
2,3,Compare vitamin K levels in raw kale vs fermen...,comparison,3,TinyLlama,True,NaN
3,4,Which has lower phytate: unfermented ogi or so...,comparison,4,Mistral,True,NaN
4,5,Compare protein quality of cowpea vs bambara n...,comparison,3,TinyLlama,True,NaN
5,6,Is palm oil or shea butter better for vitamin ...,comparison,2,TinyLlama,True,NaN
6,7,Compare iron bioavailability in raw vs sproute...,comparison,4,Mistral,True,NaN
7,8,"Which African staple has lowest phytate: fufu,...",comparison,3,TinyLlama,True,NaN
8,9,Compare glycemic index of boiled yam vs roaste...,comparison,3,TinyLlama,True,NaN
9,10,Is palm wine or fermented maize better for gut...,comparison,4,Mistral,True,NaN

In [28]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3600 entries, 0 to 3599
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                3600 non-null   int64
 1   query             3600 non-null   object
 2   label             3600 non-null   object
 3   complexity        3600 non-null   int64
 4   recommended_llm   3600 non-null   object
 5   needs_followup    3600 non-null   bool
 6   distractor_label  600 non-null    object
dtypes: bool(1), int64(2), object(4)
memory usage: 172.4+ KB